### ISSUE TITLE
Error in waf configuration 

### ISSUE THREAD

**Issue by shiphananadi** [imec-idlab/IEEE-802.11ah-ns-3#16]
I followed all the instructions from [https://www.nsnam.org/wiki/Installation#Installation](url) for the installation of ns3. 
After git clone of the repository [https://github.com/imec-idlab/IEEE-802.11ah-ns-3
](url) and while configuring waf, I get the following errors:

> XXFLAGS="-std=c++11" ./waf configure --disable-examples --disable-tests
Traceback (most recent call last):
  File "/home/shipha/Desktop/IEEE-802.11ah-ns-3/.waf3-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Node.py", line 312, in ant_iter
    raise StopIteration
StopIteration
`The above exception was the direct cause of the following exception:'

> Traceback (most recent call last):
  File "/home/shipha/Desktop/IEEE-802.11ah-ns-3/.waf3-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Scripting.py", line 110, in waf_entry_point
    run_commands()
  File "/home/shipha/Desktop/IEEE-802.11ah-ns-3/.waf3-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Scripting.py", line 167, in run_commands
    parse_options()
  File "/home/shipha/Desktop/IEEE-802.11ah-ns-3/.waf3-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Scripting.py", line 140, in parse_options
    Context.create_context('options').execute()
  File "/home/shipha/Desktop/IEEE-802.11ah-ns-3/.waf3-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Options.py", line 146, in execute
    super(OptionsContext,self).execute()
  File "/home/shipha/Desktop/IEEE-802.11ah-ns-3/.waf3-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Context.py", line 93, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/shipha/Desktop/IEEE-802.11ah-ns-3/.waf3-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Context.py", line 134, in recurse
    user_function(self)
  File "/home/shipha/Desktop/IEEE-802.11ah-ns-3/wscript", line 144, in options
    opt.load('compiler_c')
  File "/home/shipha/Desktop/IEEE-802.11ah-ns-3/.waf3-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Context.py", line 90, in load
    fun(self)
  File "/home/shipha/Desktop/IEEE-802.11ah-ns-3/.waf3-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Tools/compiler_c.py", line 36, in options
    opt.load_special_tools('c_*.py',ban=['c_dumbpreproc.py'])
  File "/home/shipha/Desktop/IEEE-802.11ah-ns-3/.waf3-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Context.py", line 321, in load_special_tools
    lst=self.root.find_node(waf_dir).find_node('waflib/extras').ant_glob(var)
  File "/home/shipha/Desktop/IEEE-802.11ah-ns-3/.waf3-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Node.py", line 361, in ant_glob
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
  File "/home/shipha/Desktop/IEEE-802.11ah-ns-3/.waf3-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Node.py", line 361, in <listcomp>
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
RuntimeError: generator raised StopIteration

Note: I am using Ubuntu 20.04 LTS
Could someone please help me?
Thanks in advance.

**Comment by asljivo1** [comment]
The following steps (as listed in the README) successfully install this instance of ns-3 on Ubuntu 18.04:
```
sudo apt-get update
sudo apt-get -y install gcc g++ python
sudo apt-get -y install gcc g++ python python-dev
sudo apt-get -y install qt4-dev-tools libqt4-dev
sudo apt-get -y install mercurial
sudo apt-get -y install bzr
sudo apt-get -y install cmake libc6-dev libc6-dev-i386 g++-multilib
sudo apt-get -y install gdb valgrind
sudo apt-get -y install gsl-bin libgslcblas0:i386
sudo apt-get -y install flex bison libfl-dev
sudo apt-get -y install tcpdump
sudo apt-get -y install sqlite sqlite3 libsqlite3-dev
sudo apt-get -y install libxml2 libxml2-dev
sudo apt-get -y install libgtk2.0-0 libgtk2.0-dev
sudo apt-get -y install vtun lxc
sudo apt -y install git
git clone https://github.com/imec-idlab/IEEE-802.11ah-ns-3.git

cd IEEE-802.11ah-ns-3

CXXFLAGS="-std=c++11" ./waf configure --disable-examples --disable-tests
./waf
```
I haven't tested it on Ubuntu 20.04 unfortunately.

**Comment by shiphananadi** [comment]
Yes, it works now.
Thanks for your help!

**Comment by Monkey-Vvvv** [comment]
Thank you！
